media:
  - name: assets
    label: Assets
    input: public/
    output: /assets
  - name: vector_assets
    label: Icons
    input: src/svg
    output: /icons
content:
  - name: config
    label: Config
    path: _config.yml
    type: file
    fields:
      - name: title
        label: Website title
        type: string
      - name: description
        label: Website description
        type: string
      - name: url
        label: Website URL
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
      - name: cover
        label: Preview image
        type: image
        description: Image used in the social preview on social networks (e.g. Facebook, Twitter...)
  - name: socials
    label: Socials
    type: collection,
    path: '_socials',
    fields:
      - name: label
        label: Label
        type: string
      - name: link
        component: url
      - name: icon
        label: Icon
        type: image
        options:
          media: vector_assets
          categories: [image]
          extensions: [svg]
  - name: projects
    label: Projects
    type: collection
    path: '_projects',
    fields:
      - name: label
        label: Label
        type: string
      - name: link
        component: url
      - name: image
        label: Image
        type: image
        options:
          media: assets
          categories: [image]
          extensions: [png,webp,jpg]
      - name: description
        label: Description
        type: rich-text
components:
  hero:
    label: Hero Section
    type: object
    fields:
      - name: headline
        label: Headline
        type: text
        required: true
      - name: cover
        label: Cover Image
        type: image
      - name: body
        label: Body Text
        type: rich-text
  card:
    label: Card Component
    type: object
    fields:
      - name: title
        label: Title
        type: text
        required: true
      - name: cover
        label: Cover Image
        type: image
      - name: description
        label: Description
        type: rich-text
      - name: button
        component: button_link
      - name: buttonTwo
        component: button_link
  icon_link:
    label: Icon Link
    type: object
    fields:
      - name: icon
        component: icon
      - name: label
        label: Label
        type: text
      - name: link
        component: url
  button_link:
    label: Button Link
    type: object
    fields:
      - name: text
        type: string
      - name: link
        component: url
  icon:
    label: Icon
    type: image
    options:
      media: vector_assets
      categories: [ image ]
      extensions: [ svg ]
  email:
    label: Email Address
    type: string
    pattern:
      regex: '^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$'
      message: 'This must be a valid email address (e.g. hello@example.com).'
  url:
    label: Link
    type: string
    pattern:
      regex: '/^https?:\/\/(?:www\.)?[-a-zA-Z0-9@:%._\+~#=]{1,256}\.[a-zA-Z0-9()]{1,6}\b(?:[-a-zA-Z0-9()@:%_\+.~#?&\/=]*)$/'
      message: 'This must be a valid website URL (e.g. https://www.wikipedia.org).'

