backend:
  name: github
  branch: main
  repo: godemperoroftheworld/portfolio
  site_domain: t2pellet.vercel.app
  base_url: https://t2pellet.vercel.app
  auth_endpoint: oauth
media_folder: "src/assets"
public_folder: "src/assets"
singletons:
  - name: "profile"
    label: "Profile"
    file: src/content/profile.yml
    fields:
      - label: Picture
        name: picture
        widget: image
      - label: Facts
        name: facts
        widget: list
        fields:
          - { label: Label, name: label, widget: string }
          - { label: Value, name: value, widget: string }
      - label: Traits
        name: traits
        widget: list
        fields:
          - { label: Label, name: label, widget: string }
          - label: Value
            name: value
            widget: list
            fields:
              - { label: "", name: content, widget: string }
