backend:
  name: github
  branch: main
  repo: godemperoroftheworld/portfolio
  site_domain: t2pellet.vercel.app
  base_url: https://t2pellet.vercel.app
  auth_endpoint: oauth
media_folder: "src/assets"
public_folder: "src/assets"
output:
  encode_file_path: true
collections:
  - name: scroller
    label: Scroller
    folder: src/content/scroller
    create: true
    identifier_field: target
    fields:
      - label: Target
        name: target
        widget: select
        options:
          - characterSheet
          - characterHistory
          - characterInventory
          - sendARaven
      - label: Title
        name: title
        widget: string
singletons:
  - name: "profile"
    label: "Profile"
    file: src/content/profile/profile.json
    fields:
      - label: Picture
        name: picture
        widget: image
      - label: Facts
        name: facts
        widget: list
        fields:
          - { label: Label, name: label, widget: string }
          - { label: Value, name: value, widget: string }
      - label: Traits
        name: traits
        widget: list
        fields:
          - { label: Label, name: label, widget: string }
          - label: Value
            name: value
            widget: list
            field:
              widget: string
      - label: Scroller
        name: scroller
        widget: relation
        collection: scroller

