backend:
  name: github
  branch: main
  repo: godemperoroftheworld/portfolio
  site_domain: t2pellet.vercel.app
  base_url: https://t2pellet.vercel.app
  auth_endpoint: oauth
media_folder: "src/assets"
public_folder: "@assets"
output:
  encode_file_path: true
i18n:
  default_locale: en
  locales:
    - en
    - fr
  structure: multiple_folders
collections:
  - name: stats
    label: Stats
    folder: src/content/stats
    create: true
    i18n: true
    identifier_field: id
    fields:
      - { label: ID, name: id, widget: string, i18n: duplicate }
      - { label: Label, name: label, widget: string, i18n: true }
      - { label: Value, name: value, widget: number, i18n: duplicate }
  - name: links
    label: Links
    folder: src/content/links
    create: true
    identifier_field: label
    fields:
      - { label: Icon, name: icon, widget: image }
      - { label: Label, name: label, widget: string }
      - { label: URL, name: href, widget: string, required: false }
      - { label: "Is Large?", name: large, widget: boolean, required: false }
  - name: section
    label: Sections
    folder: src/content/section
    create: true
    i18n: true
    identifier_field: target
    fields:
      - label: Target
        name: target
        widget: select
        options:
          - characterProfile
          - characterSheet
          - characterHistory
          - characterInventory
          - sendARaven
        i18n: duplicate
      - label: Title
        name: title
        widget: string
        i18n: true
      - label: Prompt
        name: prompt
        widget: string
        required: false
        i18n: true
      - label: Order
        name: order
        widget: hidden
singletons:
  - name: seo
    label: SEO
    file: src/content/seo/{{locale}}/seo.json
    i18n: true
    fields:
      - label: Title
        name: title
        widget: string
        i18n: true
      - label: Description
        name: description
        widget: string
        i18n: true
  - name: "profile"
    label: "Profile"
    file: src/content/profile/{{locale}}/profile.json
    i18n: true
    fields:
      - label: Picture
        name: picture
        widget: image
        i18n: duplicate
      - label: Facts
        name: facts
        widget: list
        i18n: true
        fields:
          - { label: Label, name: label, widget: string, i18n: true }
          - { label: Value, name: value, widget: string, i18n: true }
      - label: Traits
        name: traits
        widget: list
        i18n: true
        fields:
          - { label: Label, name: label, widget: string, i18n: true }
          - label: Value
            name: value
            widget: list
            i18n: true
            field:
              widget: string
              i18n: true
      - label: Scroller
        name: section
        widget: relation
        i18n: duplicate
        collection: section
  - name: sheet
    label: Sheet
    file: src/content/sheet/{{locale}}/sheet.json
    i18n: true
    fields:
      - label: Stats
        name: stats
        widget: object
        i18n: true
        fields:
          - { label: Title, name: title, widget: string, i18n: true }
      - label: Skills
        name: skills
        widget: object
        i18n: true
        fields:
          - { label: Title, name: title, widget: string, i18n: true }
          - label: Entries
            name: entries
            widget: list
            i18n: true
            fields:
              - { label: Name, name: name, widget: string, i18n: true }
              - { label: Stat, name: stat, widget: relation, collection: stats, i18n: duplicate }
      - label: Features
        name: features
        widget: object
        i18n: duplicate
        fields:
          - { label: Title, name: title, widget: string, i18n: true }
          - label: Entries
            name: entries
            widget: list
            i18n: true
            fields:
              - { label: Name, name: name, widget: string, i18n: true }
              - { label: Stat, name: stat, widget: relation, collection: stats, i18n: duplicate }
              - { label: Description, name: description, widget: string, i18n: true }
      - label: Proficiencies
        name: proficiencies
        widget: object
        i18n: true
        fields:
          - { label: Title, name: title, widget: string, i18n: true }
          - label: Value
            name: value
            widget: list
            i18n: duplicate
            field:
             widget: relation
             collection: links
             i18n: true
          - label: "Value (Two)"
            name: valueTwo
            widget: list
            i18n: duplicate
            field:
              widget: relation
              collection: links
              i18n: true
      - label: Scroller
        name: section
        widget: relation
        collection: section
        i18n: duplicate
  - name: history
    label: History
    file: src/content/history/{{locale}}/history.json
    i18n: true
    fields:
      - { label: Title, name: title, widget: string, i18n: true }
      - label: Events
        name: events
        widget: list
        i18n: true
        fields:
          - { label: Label, name: label, widget: string, i18n: trues }
          - { label: Description, name: description, widget: string, i18n: true }
          - { label: Coordinate, name: coordinate, widget: map, type: Point, i18n: duplicate }
          - { label: Icon, name: icon, widget: image, i18n: duplicate }
          - { label: "Start Date", name: startDate, widget: datetime, i18n: duplicate }
          - { label: "End Date", name: endDate, widget: datetime, required: false, i18n: duplicate }
      - label: Scroller
        name: section
        widget: relation
        collection: section
        i18n: duplicate
  - name: inventory
    label: Inventory
    file: src/content/inventory/{{locale}}/inventory.json
    i18n: true
    fields:
      - { label: Title, name: title, widget: string, i18n: true }
      - label: Projects
        name: projects
        widget: list
        i18n: true
        fields:
          - { label: Title, name: title, widget: string, i18n: duplicate }
          - { label: Icon, name: icon, widget: image, i18n: duplicate }
          - { label: Description, name: description, widget: string, i18n: true }
          - { label: URL, name: url, widget: string, required: false, i18n: duplicate }
          - label: Links
            name: links
            widget: list
            i18n: duplicate
            field:
              widget: relation
              collection: links
              i18n: duplicate
      - { label: Scroller, name: section, widget: relation, collection: section, i18n: duplicate }
  - name: contact
    label: Contact
    file: src/content/contact/{{locale}}/contact.json
    i18n: true
    fields:
      - { label: Title, name: title, widget: string, i18n: true }
      - { label: "Line One Text", name: lineOneText, widget: string, i18n: true }
      - { label: "Line Two Text", name: lineTwoText, widget: string, i18n: true }
      - label: Links
        name: links
        widget: list
        i18n: duplicate
        field:
          widget: relation
          collection: links
          i18n: duplicate
